# Generated by Django 3.2.2 on 2021-05-19 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Uttar Pradesh', 'Uttar Pradesh'), ('Haryana', 'Haryana'), ('Gujrat', 'Gujrat'), ('Bihar', 'Bihar'), ('Assam', 'Assam'), ('Jharkhand', 'Jharkhand'), ('New Delhi', 'New Delhi')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear'), ('MO', 'Motivational'), ('RL', 'Light Romantic'), ('RD', 'Dark Romantic'), ('H', 'Pure Horror'), ('HC', 'Horror+Comedy'), ('N', 'Manga')], max_length=2),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.product')),
            ],
        ),
    ]
